cilium/cilium.io

src/pages/index.jsx

This pull request moves the tweet cards after the Community section on the Home page.
**Screenshots**

fix: move tweet cards

---

src/components/shared/header/header.jsx

This PR brings an update to header display on the pages with a search field in the header
This PR also changes the breakpoint for the mobile menu display from 1280px to 1024px
Steps to test:
1. Go to [/blog](https://deploy-preview-62--cilium.netlify.app/blog/) page
2. Confirm that header looks fine on all the screen dimensions

fix: update header on 1024-1280px screens

---

static/_redirects

This pull request brings the redirect for `/install-aws-marketplace` to https://isovalent.com/install-aws-marketplace.

chore: add redirect for install-aws-marketplace page

---

gatsby-config.js

This PR brings Content Security Policy headers to add instruqt.com and play.instruqt.com to allowed frame-ancestors

feat: add CSP for frame-ancestors

---

src/posts/2021-12-09-release-1.11/index.md

This PR bring an ogImage link fix for the 1.11 release external blog post.

fix: fix 1.11-release blog post cover link

---

src/components/pages/enterprise/training/training.jsx

This PR brings an update for the Training section on the [Enterprise](https://deploy-preview-97--cilium.netlify.app/enterprise) page

feat: add labs link to training section

---

gatsby-config.js

This pull request brings the external URLs to the blog RSS feed.

fix: add external urls to rss feed

---

netlify.toml
static/_redirects

Adding it to netlify.toml didn't work.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

Move blog.cilium.io redirect rule to static/_redirects

---

static/_redirects

Redirecting to relative URL doesn't work, I'm guessing it's because blog.cilium.io/blog/ gets redirected to blog.cilium.io/blog/blog/.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

Redirect blog.cilium.io/* to cilium.netlify.app/blog/:splat

---

static/_redirects

Redirect https://blog.cilium.io/ to https://cilium.io/blog/ with 301.
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

Redirect https://blog.cilium.io/ to https://cilium.io/blog/

---

.env.example
gatsby-node.js
src/components/pages/newsletter/issues/issues.jsx

This pull request replaces the Hubspot API key with an access token as [API keys are being deprecated November 30.](https://developers.hubspot.com/changelog/upcoming-api-key-sunset)
**TODO**

fix: replace hubspot api key with access token

---

gatsby-node.js
src/components/shared/github-stars/github-stars.jsx

This pull request brings the update for github stars node, replacing `createResolvers` with `sourceNodes`. According to Gatsby docs, with v4 creating nodes inside `createResolvers` is not allowed. ([More info](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#2-data-mutations-need-to-happen-during-sourcenodes-or-oncreatenode))

fix: create github stars nodes inside sourceNodes

---

src/components/pages/adopters/logos/logos.jsx
src/components/shared/user-community/user-community.jsx
src/pages/adopters.jsx

This pull request brings anchors for the sections on Adopters page
- Deploy on your preferred cloud: `#preferred-cloud`
- Use your favorite Kubernetes distribution: `#kubernetes-distribution`
- Cilium is everywhere: `cilium-is-everywhere`

feat: add anchors to sections on Adopters page

---

src/posts/2021-05-11-cni-benchmark/index.md

This PR fixes the blog post navigation
[Preview](https://deploy-preview-246--cilium.netlify.app/blog/2021/05/11/cni-benchmark/)

feat: fix links in a blog post

---

src/pages/adopters.jsx
src/utils/case-studies-data.js

**This PR:**
Add the clickhouse card to the top section of the Adopters page;
**Steps to test**
- Open the [Adopters page](https://deploy-preview-280--cilium.netlify.app/adopters/)
- Confirm that everything looks and works as expected

feat: move clickhouse to the top section

---

src/utils/case-studies-data.js

This PR:
Adds case study to Bloomberg card in the top section of the Adopters page;
Steps to test
Open the [Adopters page](https://deploy-preview-319--cilium.netlify.app/adopters/)
Confirm that everything looks and works as expected

add case study to bloomberg card

---

src/posts/2021-05-11-cni-benchmark/index.md

Adding Performance Impact of Sidecar in the CNI benchmark Blog as a step to enhance cross blog visibility.
Adding numbers from https://isovalent.com/blog/post/cilium-service-mesh/ to https://cilium.io/blog/2021/05/11/cni-benchmark/ as a first step.

Adding Performance Impact of Sidecar in the CNI benchmark Blog

---

src/components/pages/enterprise/training/training.jsx

This pull request brings add link, that goes to [listing-cilium-distributions](https://github.com/cilium/cilium.io/blob/main/CONTRIBUTING.md#listing-cilium-distributions)
Source [issue](https://github.com/cilium/cilium.io/issues/363)
Steps to check:
- open preview
- make sure that everything looks and feels as expected

feat: add link to Listing distributions

---

src/components/pages/get-started/learn/learn.jsx

No need for an article before "Cilium", let's change "the Cilium" to simply "Cilium".

fix: typo ("the Cilium")

---

src/pages/use-cases/transparent-encryption.jsx

possibly (definitely) the "smallest" PR i've ever raised 🤏  came across it while doing some research/dev, so figured I'd fix it ✨

fix: correct grammar on 'use-cases' page for `sectionContent1`

---

gatsby-config.js

This removes the `ignore` line that is hiding the blog post from Monday about software over hardware networking.

Re-release the blog post (sw over hw)

---

src/components/pages/events/events-board/event-card/event-card.jsx

**Describe what changes this pull request brings**
Fix default cover's size for event cards
| before | after |
|---|---|
| <img width="624" alt="image" src="https://github.com/user-attachments/assets/0c81b2f8-f115-435b-8d70-e73acf4baabd"> | <img width="619" alt="image" src="https://github.com/user-attachments/assets/989498eb-379e-402b-8df3-0b74cbd4335d"> |
**Steps to check:**
1. Open [preview](https://deploy-preview-550--cilium.netlify.app/events/)
2. Make sure that everything looks and works as expected

fix: event cards cover

---

src/posts/2020-11-10-cilium-19/index.md

I think the PDF document is the same? At least the file itself has the same name, `44824.pdf`.

fix: Cilium 1.9 release blog: Fix broken link to Maglev paper

---

.gitignore
README.md

This PR fixes several issues on the README:
- chore: add .idea/ to .gitignore
- docs: fix TOC anchor for “Run the built website”
- docs: update “Getting Started” to use fork-and-clone workflow

docs: Fix TOC on README and Getting Started instructions

---

src/pages/adopters.jsx

This PR fixes the issue #650 
**What it does** 
- Add overflow-x-hidden to the whole page to prevent scrolling
- Add w-full to acquire the full width of the screen
**Screenshot showing a page without horizontal scrolling**

Fix Horizontal scrolling bug in adopters route

---

src/hooks/use-click-outside.js

Closes: #617, #619 
The [use-click-outside.js](https://github.com/cilium/cilium.io/blob/main/src/hooks/use-click-outside.js#L12) was registering multiple event listeners on every render, causing the handler function to run multiple times per click which is unnecessary and bad code.
Solution: Uses empty dependency array to register listeners only once.

bug: Fix duplicate event listeners in useClickOutside hook

---

src/utils/seo-metadata.js

Added the metadata for homePage in src/utils/metadata.js
this fix #676

fix: add missing metadata for homepage (#676)

---

src/components/pages/home/hero/hero.jsx

- This PR fixes the layout of the hero illustration on large screens. The issue arose after the image was migrated from a standard <img> tag to the StaticImage .
- The previous styling worked correctly with the `<img>` tag, but the new component introduced layout shifts and sizing issues. 
--- 
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/85924230-01ce-445c-9a23-7cbe30629525" width="400"/></td>
<td><img src="https://github.com/user-attachments/assets/e2fad2ea-ff2d-4bb2-8b46-3013e5dd51d7" width="400"/></td>
</tr>
</table>

Fix: Adjust hero illustration size

---

src/components/pages/enterprise/training/training.jsx

I searched through the academy and couldn't find any courses related to Cilium and the current link doesn't work. Happy to leave this open for a few weeks if someone can come along and correct me.

fix: remove dead link to Solo training

---

src/pages/industries/ai.jsx
src/pages/industries/cloud-providers.jsx
src/pages/industries/consulting.jsx
src/pages/industries/e-commerce.jsx
src/pages/industries/edge-computing.jsx
src/pages/industries/financial-services.jsx
src/pages/industries/media-entertainment.jsx
src/pages/industries/security.jsx
src/pages/industries/software.jsx
src/pages/industries/telcos-datacenters.jsx
src/utils/seo-metadata.js

Fixes #681
This PR introduces a clean-up fix for the SEO metadata across the industries pages, improving consistency and optimization. The updated descriptions are concise, SEO-friendly, and better capture the essence of each page.
The existing descriptions for the industries pages were overly generic. I refined them to be more specific, highlight unique value propositions, and improve SEO performance.
Other sections like /blog, /blog-post, /events, and /labs already handle metadata dynamically through the shared component, so no changes were needed there.
Clean-up fix for meta descriptions in industries pages:
/consulting
/e-commerce
/financial-services
/media-entertainment
/security
/software
/telcos-datacenters
Ensured the new descriptions are concise, relevant, and SEO-friendly.

feat(seo): add metadata for /get-started page (#681)

---

README.md

- While contributing to the Cilium website using my MacBook Air M2, I noticed the laptop would heat up significantly during builds and while running npm run develop. Since the MacBook Air has no fan, this quickly became an issue.
- After experimenting, I realized that limiting Gatsby to fewer CPU cores (GATSBY_CPU_COUNT=2 npm run develop) greatly reduced both heat and memory usage, making development much smoother.
- Changes
- Updated the README troubleshooting section.
- Added guidance for laptops without fans (e.g., MacBook Air) on using GATSBY_CPU_COUNT=2 npm run develop.
- This will help contributors who use lightweight, fanless laptops avoid overheating and resource issues when working with the site.

docs: add guidance for laptops without fans to reduce Gatsby resource usage
