src/posts/2022-03-05-troubleshoot-cilium-network-policy/index.md

add - to solve #34

---

src/utils/case-studies-data.js

Fix typo in case studies
Signed-off-by: Youssef Azrak <yazrak.tech@gmail.com>

Fix typo in case studies

---

src/components/shared/hands-on/hands-on.jsx

This PR updates the instruqt link in the Hands-on section

fix: update hands-on section link

---

src/components/pages/home/highlights/highlights.jsx

we support more k8s service types than just load balancer

update section title

---

src/posts/2022-01-25-cilium-service-mesh-feedback/index.md
src/posts/2022-04-12-multi-cluster-networking/index.md
src/posts/2022-05-05-meet-Laurent/index.md

change what is featured and popular on the blog

---

src/posts/2022-05-10-kubecon-eu-talks/index.md

fix kubecon talks slug

---

src/components/shared/seo/seo.jsx

This PR updates the canonical URL in Helmet

fix: fix canonical url for pages

---

src/posts/2022-05-10-kubecon-eu-talks/index.md

add service mesh panel

---

src/posts/2022-05-21-cloud-unfiltered-podcast-dan/index.md

add cloud unfiltered podcast

---

src/posts/2022-05-18-k8s-from-scratch/index.md

add k8s from scratch blog

---

src/posts/2022-05-15-cncf-paris/index.md

add cncf paris meetup

---

src/posts/2021-12-01-service-mesh-beta/index.md
src/posts/2021-12-20-github-10k/index.md
src/posts/2022-01-25-cilium-service-mesh-feedback/index.md

switch 10k for service mesh as popular

---

src/posts/2022-06-01-dual-stack/index.md

add dual stack blog

---

src/posts/2022-06-16-TNS-tetragon/index.md

add TNS tetragon

---

src/posts/2022-06-16-kubermatic-walkthrough/index.md

add kubermatic blog

---

src/posts/2022-06-10-live-migrate-meltwater/index.md

add meltwater video

---

src/posts/2022-01-25-cilium-service-mesh-feedback/index.md
src/posts/2022-05-10-kubecon-eu-talks/index.md
src/posts/2022-06-16-TNS-tetragon/index.md
src/posts/2022-06-16-kubermatic-walkthrough/index.md

change featured posts

---

src/posts/2022-05-11-meltwater-meetup/index.md
src/posts/2022-05-16-tetragon/index.md

add meltwater meetup and fix tetragon image

---

src/posts/2022-07-13-L4LB-XDP/index.md

update Github link to title

---

src/posts/2022-06-16-TNS-tetragon/index.md
src/posts/2022-07-20-112-release/index.md

add 1.12 release blog

---

src/posts/2022-20-07-cilium-service-mesh/index.md

add service mesh blog

---

src/posts/2022-07-20-cncf-112-release/index.md

add CNCF release blog

---

src/posts/2022-07-21-tfir-release/index.md

TFIR Release 1.12

---

src/posts/2022-07-21-oracle-cloud/index.md

add oracle cloud

---

src/posts/2022-07-22-first-impression/index.md

add first impressions blog

---

src/posts/20220-07-26-future-interview/index.md

add future interview

---

src/posts/2022-07-25-nexxiot-case-study/index.md

add Nexxiot user story

---

src/posts/2022-07-25-cilium-with-datadog/index.md

add cilium with datadog

---

src/posts/2022-07-25-monitor-with-hubble/index.md

add monitoring with Hubble

---

src/posts/2022-07-22-heise-112-release/index.md

add Heise Release

---

src/posts/2022-07-25-key-monitoring-metrics/index.md

add key metrics datadog blog

---

src/posts/2022-07-22-itpro-today-release/index.md

add ITPro Release Blog

---

src/posts/2022-07-21-itworld-release/index.md

add ITWorld release

---

src/posts/2022-07-27-cilium-nos/index.md

add cilium nos blog

---

src/posts/2022-07-28-release-informatique/index.md

add informtique release

---

gatsby-node.js
src/components/shared/github-stars/github-stars.jsx

This PR brings an update for the Cilium github stars fetching to avoid build failures when the github API refuses to connect

chore: add github stars errors

---

src/posts/2022-08-04-tetragon-nim/index.md

add tetragon blog

---

src/posts/2022-08-21-ebpf-exploitation/index.md

add Learning eBPF exploitation

---

src/components/pages/enterprise/training/training.jsx
src/components/shared/hands-on/hands-on.jsx

[Preview](https://deploy-preview-159--cilium.netlify.app/)

chore: update tutorials link

---

src/posts/2022-10-27-cilium-graduation/index.md

Signed-off-by: Thomas Graf <thomas@cilium.io>

fix: fix PR link

---

src/posts/2022-07-20-112-release/index.md
src/posts/2022-10-18-kubecon-talks/index.md
src/posts/2022-10-27-cilium-graduation/index.md
src/posts/2022-10-30-grafana-demo/index.md
src/posts/2022-11-04-kubecon-wrapup/index.md

change featured and popular posts

---

src/posts/2022-11-11-debug-np/index.md

add troubleshooting blog

---

src/components/shared/blog-post-card/blog-post-card.jsx
src/utils/use-element-rect.js
tailwind.config.js

This PR fixes the appearance of the post cover.
To check everything works as expected go [here](https://deploy-preview-199--cilium.netlify.app/) and look at Learn about Cilium & eBPF section, blogpost without cover image should have proper image placeholder.

fix: post cover fix

---

src/components/pages/newsletter/cards/cards.jsx

update grammar on the newsletter page

---

src/utils/case-studies-data.js

add link to blog for retailer

---

src/components/pages/get-help/faq/item/item.jsx
src/components/pages/telling-story/hero/form/form.jsx
src/components/shared/header/burger/burger.jsx
src/components/shared/mobile-menu/mobile-menu.jsx
src/components/shared/mobile-menu/submenu/submenu.jsx
src/components/shared/subscribe-form/subscribe-form.jsx

This pull request reduces the framer-motion bundle size following the guide https://www.framer.com/docs/guide-reduce-bundle-size/ 
**Step to steps**
- Open [deploy preview](https://deploy-preview-211--cilium.netlify.app/)
- Check components where framer-motion was used (burger, mobile menu, [subscribe form](https://deploy-preview-211--cilium.netlify.app/newsletter), [telling-story form](https://deploy-preview-211--cilium.netlify.app/telling-story))

feat: reduce framer-motion bundle size

---

src/utils/case-studies-data.js

Update Sky Adopters card

---

src/posts/2023-02-06-wtf/index.md

fix WTF blog

---

README.md

Added the example command `cp .env.example .env` under [bullet 3](https://github.com/Neilblaze/cilium.io/blob/main/README.md#:~:text=Copy%20.env.example%20and%20rename%20it%20into%20.env) in Getting Started.
Fixes: #244 
cc: @xmulligan, @Oms-343

fix: rephrased setup command

---

src/pages/use-cases/bandwidth-optimization.jsx
src/pages/use-cases/bgp.jsx
src/pages/use-cases/protocol-visibility.jsx

Small spelling fixes for the new use case pages

---

src/posts/2022-11-03-constellation/index.md

We found V1 of the post a bit hard to read. So here's V2 with contributions from the original authors @m1ghtym0 and @3u13r. Hope this works for you. Thank you very much.

Re-write blog post on Constellation 

---

src/utils/case-studies-data.js

This PR adds the meltwater case study to the Meltwater card in the adopters page

Update adopters page

---

src/posts/2021-05-11-cni-benchmark/index.md

Revert "Update the date in the blog when the new sidecar data was added"

---

src/posts/2023-08-13-k3s/index.md
src/posts/2023-09-02-eni-prefix/index.md
src/posts/2023-09-05-tetragon-without-cilium/index.md

This PR changes the `How To`category -> `How-To`

fix category name

---

src/components/shared/user-community/user-community.jsx
src/utils/case-studies-data.js

**This PR:**
- Updates card design;
**Preview**
- Preview [Home page](https://deploy-preview-349--cilium.netlify.app/)
**Steps to test**

style: update design card

---

src/pages/industries/cloud-providers.jsx
src/pages/industries/consulting.jsx
src/pages/industries/e-commerce.jsx
src/pages/industries/financial-services.jsx
src/pages/industries/media-entertainment.jsx
src/pages/industries/security.jsx
src/pages/industries/software.jsx
src/pages/industries/telcos-datacenters.jsx

Add seo meta-data for industry pages

---

src/components/shared/user-community/images/deezer.inline.svg
src/components/shared/user-community/user-community.jsx
src/pages/adopters.jsx
src/utils/case-studies-data.js

This PR adds Deezer to Cilium's users list

add deezer to users list

---

src/utils/case-studies-data.js

This PR adds the Adobe, Clickhouse, Seznam, and Edgeless systems talks from CiliumCon NA to the user page

update adopters links

---

src/pages/404.jsx

[Preview 404 Page](https://deploy-preview-403--cilium.netlify.app/sdfsdf)

feat: adds links to 404 page

---

src/pages/adopters.jsx
src/utils/case-studies-data.js

This PR updates the cards of the following companies with talks from CiliumCon + KubeCon NA 2023: 
- SuperOrbital
- Seznam
- Adobe
- Clickhouse
- Datadog
- Cosmonic
- Palantir

chore: update adopters with talks from CiliumCon

---

src/components/pages/get-started/architecture/architecture.jsx
src/components/pages/get-started/hero/hero.jsx
src/components/pages/get-started/learn/learn.jsx
src/components/pages/get-started/news/news.jsx
src/components/pages/get-started/related-projects/related-projects.jsx
src/components/pages/home/highlights/highlights.jsx
src/components/shared/cncf-banner/cncf-banner.jsx
src/components/shared/hands-on/hands-on.jsx
src/pages/get-started.jsx

[Preview](https://deploy-preview-433--cilium.netlify.app/get-started/)

feat: fixes get-started page

---

src/posts/2024-02-02-cilium-talks-at-kubecon-eu-2024/index.md

chore: update title

---

gatsby-config.js

This PR unpublishes Dan's blog post from the site

chore: unpublish post

---

src/posts/2024-03-07-case-study-cloud-provider/index.md

Update the date in the new user story

chore: update date

---

gatsby-config.js

Revert "ignore cloud provider story"

---

src/posts/2023-12-26-cloud-native-projects-to-watch-2024/index.md

Fix broken link on one of the blogs

chore: update link

---

src/utils/case-studies-data.js

- Add Alibaba blog on cilium.io to case study page
- remove Roche case study

chore: update adopters page

---

src/pages/use-cases/gateway-api.jsx

feat: include GAMMA in gateway api page

---

src/posts/2024-08-10-sveltos-templating/index.md

fix external blog post link and description

chore: fix link and description

---

src/components/pages/home/hero/hero.jsx

**Describe what changes this pull request brings**
Add `Start Lab` button to home page Hero
**Steps to check:**
1. Open [preview](https://deploy-preview-586--cilium.netlify.app)
2. Make sure that everything looks and works as expected

feat: add start lab button

---

src/components/shared/top-banner/index.js
src/components/shared/top-banner/top-banner.jsx
src/layouts/main/main.jsx

**Describe what changes this pull request brings**
Add top banner to Layout
**Steps to check:**
1. Open [preview](https://deploy-preview-589--cilium.netlify.app/)
2. Make sure that everything looks and works as expected

feat: add top banner

---

src/components/shared/top-banner/top-banner.jsx

**Describe what changes this pull request brings**
Minor fixes for new top banner:
- More simple structure
- Fix for text style in `Learn more`
**Steps to check:**
1. Open [preview]()
2. Make sure that everything looks and works as expected

fix: learn more link and simplified structure

---

src/components/pages/brand/brand-features/brand-features.jsx

chore: fixed typo "cillium" to cilium

---

src/components/pages/enterprise/distributions/distributions.jsx

Updated product name for enterprise distribution and website link

Update distributions with new Isovalent Enterprise name

---

src/posts/Automated-Kubernetes-Threat-Detection-with-Tetragon-and Azure-Sentinel/index.md

Building Your Security Command Centre
Transform your Kubernetes security from reactive firefighting to proactive threat hunting with automated detection and response.

Automated Kubernetes Threat Detection with Tetragon and Azure SentinelCreate index.md

---

src/components/pages/blog-post/content/content.jsx
src/components/pages/blog/posts-board/posts-board.jsx
src/components/shared/header/header.jsx
src/components/shared/popular-posts/popular-posts.jsx
tailwind.config.js

fix: dark theme text on blog pages

---

package-lock.json
package.json
src/components/shared/top-banner/top-banner.jsx

Fixed #694 ,
This PR fixes the inconsistent hover behavior of the TopBanner link in dark mode by ensuring the text color changes properly on hover.
Before : 
https://github.com/user-attachments/assets/827473b5-f8f4-41a2-95e1-3d00d2d7afa6
After :
https://github.com/user-attachments/assets/e0964250-ee17-489d-b1ba-231c6b0c428f

Fix: TopBanner link hover text-color in dark mode

---

src/components/shared/github-stars/github-stars.jsx
src/components/shared/header/header.jsx

fix: navbar overflow

---

src/pages/outcomes/cost-and-carbon-savings.jsx
src/pages/outcomes/network-automation.jsx
src/pages/outcomes/zero-trust.jsx

This PR adjusts the hero section and the sections after it for a better user experience.
cc: @xmulligan

fix: Adjust outcomes pages hero section

---

src/pages/adopters.jsx

remove fpt telecom from cloud section
